### ISSUE TITLE
Verify the Code Quality

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-api#26]
As a developer, I need to set Quality Gates conditions in order to verify if the measures got in the Static Code Analysis accomplish with the Quality expected.

**Acceptance Criteria**
-
- The GH action [sonarqube-quality-gate-check](https://github.com/marketplace/actions/sonarqube-quality-gate-check) should be used.
- A new Quality Gate should be created and set as the **default**.
- Add a new **Coverage** condition with a value of  less than 80%.
- If the Code Coverage measure accomplishes with the condition, the step should be successful.
- If not, the step should fail and all the CI workflow should also fail.

**Sources**
-
- [Managing Quality Gates](https://docs.sonarcloud.io/standards/managing-quality-gates/)

**Deadline**
-
Firday 10th, 2023

**Comment by Camiloarceg** [comment]
Hi Caleb Espinoza Gutierrez,  just to let you know we are Blocked with tickets# 25 and 26 . We couldn't set up the sonar cloud project from github and doing some research we realized that we need to set up the project from sonar cloud first, but we don't have permissions since we are not owner, can you please accept the request to allow the sonar cloud organization get the projects on our github project?

**Comment by Camiloarceg** [comment]
Setting up the project first we obtain vital information for the configuration nedde on #25 and 26:
SONAR_TOKEN
sonar.projectKey
sonar.organization

**Comment by Camiloarceg** [comment]
UPDATE: we are not block this was a false alarm I'm sorry .
