### ISSUE TITLE
Research about Cloud Providers prices and free plans

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-api#29]
As an operator, I need to decide which Cloud provider we are going to use in order to implement a CD workflow and deploy the Banking API and Web UI apps.

**Acceptance Criteria**
-
- A cloud provider should be chosen, either AWS or Azure.
- The decision should be taken as a team.
- Once chosen, two accounts (at least) should be created in that cloud provider.
- The reasons which made you choose it should be explained either in the wiki or in the comments section of this ticket.

**Sources**
-
- [AWS Free Tier](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all).
- [Azure Free Services](https://azure.microsoft.com/en-us/pricing/free-services/)

**Deadline**
-
Friday 10th, 2023

**Comment by DMGochoa** [comment]
The team has decided to use aws over azure for the following reasons:

1. The reason for choosing aws is because of the ease we had in obtaining free accounts without compromising the members' money.
2. It is one of the most representative cloud products in the market and according to some technology magazines represents about 40% of the cloud market.
